[workspace]
resolver = "2"
members = ["crates/rhizome-proto", "crates/rhizome-client", "crates/rhizome-store", "crates/rhizome-app"]

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Alp"]
license = "GPL-3.0-or-later"
repository = "https://github.com/alplix/rhizome"

[workspace.lints.rust]
missing_debug_implementations = "warn"
unreachable_pub = "warn"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
